# Generated by Django 5.0 on 2023-12-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/'),
        ),
    ]
