# Generated by Django 5.0 on 2024-01-01 11:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_images_project_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='videos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='videos'),
        ),
    ]
