# Generated by Django 5.0 on 2024-01-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_images_alter_project_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='videos',
        ),
    ]
